#!/usr/bin/env python3
"""Generate a proportional 1-bit balance font from bundled Noto Sans Regular.

Requires freetype-py from lib/EpdFont/scripts/requirements.txt. Uses the font's
proportional lining (.lf) glyphs, retaining their native bearings and advances.
The source and generated subset are licensed under the SIL Open Font License
1.1; see lib/EpdFont/builtinFonts/source/NotoSans/OFL.txt.
"""

import argparse
import hashlib
from pathlib import Path
import struct
import zlib

import freetype


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "lib/EpdFont/builtinFonts/source/NotoSans/NotoSans-Regular.ttf"
OUTPUT = ROOT / "src/components/fonts/BalanceDigits.h"
CHARACTERS = "0123456789$,. "
PIXEL_SIZE = 62
DIGIT_NAMES = ("zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine")


def rasterize():
    face = freetype.Face(str(SOURCE))
    face.set_pixel_sizes(0, PIXEL_SIZE)
    glyphs = []
    for character in CHARACTERS:
        if character.isdigit():
            name = f"{DIGIT_NAMES[int(character)]}.lf".encode("ascii")
            index = face.get_name_index(name)
            assert index and face.get_glyph_name(index) == name, f"Missing proportional glyph: {name!r}"
        else:
            index = face.get_char_index(ord(character))
            assert index, f"Missing character: {character!r}"
        face.load_glyph(index, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)
        slot = face.glyph
        bitmap = slot.bitmap
        assert bitmap.pixel_mode == freetype.FT_PIXEL_MODE_MONO
        stride = (bitmap.width + 7) // 8
        assert bitmap.pitch >= stride
        data = bytearray()
        for y in range(bitmap.rows):
            row = bytearray(bitmap.buffer[y * bitmap.pitch:y * bitmap.pitch + stride])
            if bitmap.width % 8:
                row[-1] &= (0xFF << (8 - bitmap.width % 8)) & 0xFF
            data.extend(row)
        has_ink = any(data)
        glyphs.append({
            "width": bitmap.width if has_ink else 0,
            "height": bitmap.rows if has_ink else 0,
            "left": slot.bitmap_left if has_ink else 0,
            "top": slot.bitmap_top if has_ink else 0,
            "advance": round(slot.advance.x / 64),
            "data": data if has_ink else bytearray(),
        })

    visible = [glyph for glyph in glyphs if glyph["width"] and glyph["height"]]
    top = max(glyph["top"] for glyph in visible)
    bottom = min(glyph["top"] - glyph["height"] for glyph in visible)
    height = top - bottom
    for glyph in glyphs:
        glyph["y"] = top - glyph["top"] if glyph["height"] else 0
        assert 0 <= glyph["width"] <= 255 and 0 <= glyph["height"] <= 255
        assert -128 <= glyph["left"] <= 127
        assert 0 <= glyph["y"] <= 255 and glyph["y"] + glyph["height"] <= height
        assert 1 <= glyph["advance"] <= 255
        assert len(glyph["data"]) == ((glyph["width"] + 7) // 8) * glyph["height"]
    assert all(44 <= glyph["height"] <= 46 for glyph in glyphs[:10]), "Unexpected numeral ink height"
    assert glyphs[1]["advance"] < glyphs[0]["advance"], "Proportional numerals required"
    assert sum(len(glyph["data"]) for glyph in glyphs) < 65536
    return glyphs, height


def write_header(glyphs, height):
    data = bytearray()
    metrics = []
    for character, glyph in zip(CHARACTERS, glyphs):
        metrics.append(
            f"    {{{len(data)}, {glyph['width']}, {glyph['height']}, "
            f"{glyph['left']}, {glyph['y']}, {glyph['advance']}}},  // {character if character != ' ' else 'space'}"
        )
        data.extend(glyph["data"])
    bitmap_lines = [
        "    " + ", ".join(f"0x{value:02x}" for value in data[i:i + 16]) + ","
        for i in range(0, len(data), 16)
    ]
    sha = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    header = f"""#pragma once

// Generated by scripts/generate_balance_font.py; do not edit.
// Noto Sans Regular balance subset, {PIXEL_SIZE} px, native proportional lining figures (.lf).
// Copyright 2022 The Noto Project Authors (https://github.com/notofonts/latin-greek-cyrillic).
// SIL Open Font License 1.1: lib/EpdFont/builtinFonts/source/NotoSans/OFL.txt
// Source: lib/EpdFont/builtinFonts/source/NotoSans/NotoSans-Regular.ttf
// Source SHA-256: {sha}
// FreeType: {'.'.join(map(str, freetype.version()))}

#include <cstdint>

namespace balance_font {{

struct Glyph {{
  uint16_t offset;
  uint8_t width;
  uint8_t height;
  int8_t left;
  uint8_t top;
  uint8_t advance;
}};

static constexpr int HEIGHT = {height};
static constexpr char CHARACTERS[] = "{CHARACTERS}";
// top is the downward offset from the subset's uppermost ink to the glyph.
// clang-format off
static constexpr Glyph GLYPHS[] = {{
{chr(10).join(metrics)}
}};

// Byte-aligned rows, most significant bit first, set bit = ink.
static constexpr uint8_t BITMAPS[] = {{
{chr(10).join(bitmap_lines)}
}};
// clang-format on

static_assert(sizeof(GLYPHS) / sizeof(GLYPHS[0]) == sizeof(CHARACTERS) - 1);
static_assert(sizeof(BITMAPS) < 65536);

}}  // namespace balance_font
"""
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(header)
    print(f"Wrote {OUTPUT.relative_to(ROOT)}: {len(data)} bitmap bytes, {height}px total ink height")
    print(f"Native proportional advances: 1={glyphs[1]['advance']}px, 0={glyphs[0]['advance']}px")


def write_preview(path, glyphs, height):
    samples = ("$1,175", "$1,175.50", "$0", "$10,000", "$999,999,999.50")
    lookup = dict(zip(CHARACTERS, glyphs))
    width = max(560, max(sum(lookup[c]["advance"] for c in sample) for sample in samples) + 48)
    image_height = (height + 40) * len(samples) + 40
    pixels = [bytearray([255]) * width for _ in range(image_height)]
    for row, sample in enumerate(samples):
        x = (width - sum(lookup[c]["advance"] for c in sample)) // 2
        for character in sample:
            glyph = lookup[character]
            stride = (glyph["width"] + 7) // 8
            for gy in range(glyph["height"]):
                for gx in range(glyph["width"]):
                    if glyph["data"][gy * stride + gx // 8] & (0x80 >> (gx % 8)):
                        px = x + glyph["left"] + gx
                        py = 20 + row * (height + 40) + glyph["y"] + gy
                        assert 0 <= px < width and 0 <= py < image_height
                        pixels[py][px] = 0
            x += glyph["advance"]

    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))

    png = b"\x89PNG\r\n\x1a\n"
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", width, image_height, 8, 0, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(b"".join(b"\0" + row for row in pixels)))
    png += chunk(b"IEND", b"")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(png)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--preview", type=Path, help="Write a PNG proof of the generated glyphs")
    args = parser.parse_args()
    glyphs, height = rasterize()
    write_header(glyphs, height)
    if args.preview:
        write_preview(args.preview, glyphs, height)


if __name__ == "__main__":
    main()
