#!/usr/bin/env python3
"""Generate the countdown's numeric-only 1-bit font from bundled Chakra Petch.

Requires freetype-py from lib/EpdFont/scripts/requirements.txt. The source font
and this generated subset are licensed under the SIL Open Font License 1.1;
see lib/EpdFont/builtinFonts/source/ChakraPetch/OFL.txt.
"""

import argparse
import hashlib
from pathlib import Path
import struct
import zlib

import freetype


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "lib/EpdFont/builtinFonts/source/ChakraPetch/ChakraPetch-Bold.ttf"
OUTPUT = ROOT / "src/components/fonts/CountdownDigits.h"
CHARACTERS = "0123456789:"
DIGIT_SIZE = 169
COLON_SIZE = 128


def rasterize():
    face = freetype.Face(str(SOURCE))
    glyphs = []
    for character in CHARACTERS:
        face.set_pixel_sizes(0, COLON_SIZE if character == ":" else DIGIT_SIZE)
        face.load_char(character, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_MONO)
        slot = face.glyph
        bitmap = slot.bitmap
        stride = (bitmap.width + 7) // 8
        data = bytearray()
        for y in range(bitmap.rows):
            row = bytearray(bitmap.buffer[y * bitmap.pitch:y * bitmap.pitch + stride])
            if bitmap.width % 8:
                row[-1] &= 0xFF << (8 - bitmap.width % 8)
            data.extend(row)
        glyphs.append({
            "width": bitmap.width,
            "height": bitmap.rows,
            "left": slot.bitmap_left,
            "top": slot.bitmap_top,
            "advance": round(slot.advance.x / 64),
            "data": data,
        })

    top = max(glyph["top"] for glyph in glyphs[:10])
    bottom = min(glyph["top"] - glyph["height"] for glyph in glyphs[:10])
    height = top - bottom
    # Center proportional outlines in equal-width cells so the timer never shifts.
    digit_advance = max(glyph["advance"] for glyph in glyphs[:10])
    for glyph in glyphs[:10]:
        glyph["y"] = top - glyph["top"]
        glyph["advance"] = digit_advance
        glyph["left"] = (digit_advance - glyph["width"]) // 2
    glyphs[10]["y"] = (height - glyphs[10]["height"]) // 2
    assert len({glyph["advance"] for glyph in glyphs[:10]}) == 1, "Digits must be tabular"
    return glyphs, height


def write_header(glyphs, height):
    data = bytearray()
    metrics = []
    for character, glyph in zip(CHARACTERS, glyphs):
        metrics.append(
            f"    {{{len(data)}, {glyph['width']}, {glyph['height']}, "
            f"{glyph['left']}, {glyph['y']}, {glyph['advance']}}},  // {character}"
        )
        data.extend(glyph["data"])
    assert len(data) < 65536
    min_bearing = min(glyph["left"] for glyph in glyphs[:10])
    max_right = max(glyph["left"] + glyph["width"] for glyph in glyphs[:10])
    right_bearing = glyphs[0]["advance"] - max_right
    bitmap_lines = [
        "    " + ", ".join(f"0x{value:02x}" for value in data[i:i + 16]) + ","
        for i in range(0, len(data), 16)
    ]
    sha = hashlib.sha256(SOURCE.read_bytes()).hexdigest()
    header = f"""#pragma once

// Generated by scripts/generate_countdown_font.py; do not edit.
// Chakra Petch Bold numeric subset, {DIGIT_SIZE} px digits / {COLON_SIZE} px colon.
// Copyright 2018 The Chakra Petch Project Authors (https://github.com/m4rc1e/Chakra-Petch.git).
// SIL Open Font License 1.1: lib/EpdFont/builtinFonts/source/ChakraPetch/OFL.txt
// Source SHA-256: {sha}
// FreeType: {'.'.join(map(str, freetype.version()))}

#include <cstdint>

namespace countdown_font {{

struct Glyph {{
  uint16_t offset;
  uint8_t width;
  uint8_t height;
  uint8_t left;
  uint8_t top;
  uint8_t advance;
}};

static constexpr int HEIGHT = {height};
static constexpr int LEFT_BEARING = {min_bearing};
static constexpr int RIGHT_BEARING = {right_bearing};
// clang-format off
static constexpr Glyph GLYPHS[] = {{
{chr(10).join(metrics)}
}};

// Row-major BW1 masks, most significant bit first, set bit = ink.
static constexpr uint8_t BITMAPS[] = {{
{chr(10).join(bitmap_lines)}
}};
// clang-format on

}}  // namespace countdown_font
"""
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(header)
    print(f"Wrote {OUTPUT.relative_to(ROOT)}: {len(data)} bitmap bytes, {height}px ink height")


def write_preview(path, glyphs, height):
    samples = ("25:00", "50:00", "90:00", "180:00")
    longest_run = max(sum(glyphs[10 if char == ":" else int(char)]["advance"] for char in sample)
                      for sample in samples)
    width, image_height = max(560, longest_run + 40), (height + 40) * len(samples) + 40
    pixels = [bytearray([255]) * width for _ in range(image_height)]
    for row, sample in enumerate(samples):
        run = [glyphs[10 if char == ":" else int(char)] for char in sample]
        x = (width - sum(glyph["advance"] for glyph in run)) // 2
        for glyph in run:
            stride = (glyph["width"] + 7) // 8
            for gy in range(glyph["height"]):
                for gx in range(glyph["width"]):
                    if glyph["data"][gy * stride + gx // 8] & (0x80 >> (gx % 8)):
                        pixels[40 + row * (height + 40) + glyph["y"] + gy][x + glyph["left"] + gx] = 0
            x += glyph["advance"]

    def chunk(kind, data):
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))

    png = b"\x89PNG\r\n\x1a\n"
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", width, image_height, 8, 0, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(b"".join(b"\0" + row for row in pixels)))
    png += chunk(b"IEND", b"")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(png)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--preview", type=Path, help="Write a PNG proof of the generated glyphs")
    args = parser.parse_args()
    glyphs, height = rasterize()
    write_header(glyphs, height)
    if args.preview:
        write_preview(args.preview, glyphs, height)


if __name__ == "__main__":
    main()
